### PR TITLE
ZCS-4915: Intergation of reporting scripts with new framework

### PR DESCRIPTION
**Pull request by sakchhi-kiran**
Added code to create reports for the executing tests.

### CODE REVIEW

**Comment by fatkudu** [comment]
Not terribly happy having jar files committed to git.  Can't we build these/get them from elsewhere?

**Comment by sakchhi-kiran** [comment]
@fatkudu I have create a new task to remove these dependencies.

**Comment by tmclane** [comment]
@sakchhi-kiran The problem with binary files and git is that once they are in there you can't remove them. They stay in the history forever and this causes the repository to balloon in size. I would say it is frowned upon as far as usage goes.

**Comment by gordyt** [comment]
@tmclane is exactly correct.  @sakchhi-kiran you need to split up the commit(s) that checked in binary files and remove them..  Once that has been done you can force push the updated branch and that will let the orphaned improper commits get garbage collected. Please make sure this gets done.

**Pull request merged**
